---
feeds:
- https://aws.amazon.com/blogs/security/feed/
- https://news.ycombinator.com/rss
- https://www.archlinux.org/feeds/news/
- https://www.bleepingcomputer.com/feed/
- https://www.itworldcanada.com/feed
- https://www.reddit.com/r/golang/.rss
- https://www.reddit.com/r/linux/.rss
- https://www.zdnet.com/topic/security/rss.xml
# Optionally define an application to view the feeds
externalViewer: chromium
