# Don't print a new line at the start of the prompt
add_newline = false

[character]
error_symbol = "[✖](bold red) "

[gcloud]
disabled = true

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
